/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Suspense } from 'react'
import { Canvas } from '@react-three/fiber'
import { OrbitControls } from '@react-three/drei'
import Lights from './Lights'

import './styles.css'
import { Frame } from './components/Frame'
import { PlaneMask } from './components/PlaneMask'
import Ladies from './components/Ladies'
import { useControls, folder, Leva } from 'leva'

const portraitMode = window.matchMedia('(orientation: portrait)').matches

const modelOptions = (Key) => {
  const mainObj = {
    Standing: 1,
    Ducking: 2,
    PointingGun: 3,
    Running: 4,
  }

  const returnOBJ = mainObj[Key]
    ? { ...{ [Key]: mainObj[Key] }, ...mainObj }
    : mainObj

  return {
    options: returnOBJ,
  }
}

export default function App() {
  const {
    FrontModel,
    BackModel,
    FrontColor,
    LeftModel,
    RightModel,
    TopModel,
    BottomModel,
    BackColor,
    LeftColor,
    RightColor,
    TopColor,
    BottomColor,
    Show,
  } = useControls({
    Front: folder({
      FrontModel: modelOptions('Standing'),
      FrontColor: '#ffadad',
    }),
    Right: folder({
      RightModel: modelOptions('Ducking'),
      RightColor: '#caffbf',
    }),
    Back: folder({
      BackModel: modelOptions('Running'),
      BackColor: '#a0c4ff',
    }),
    Left: folder({
      LeftModel: modelOptions('PointingGun'),
      LeftColor: '#fdffb6',
    }),
    Top: folder({
      TopModel: modelOptions('PointingGun'),
      TopColor: '#bdb2ff',
    }),
    Bottom: folder({
      BottomModel: modelOptions('PointingGun'),
      BottomColor: '#ffc6ff',
      Show: { value: true, label: 'Show Floor' },
    }),
  })

  return (
    <>
      <Leva collapsed={false} />
      <Canvas
        camera={{ position: [0, 0, portraitMode ? 5 : 3] }}
        colorManagement
        shadows
        dpr={[1, 2]}
      >
        <OrbitControls />
        <directionalLight position={[1, 2, 5]} intensity={1} />
        <ambientLight intensity={0.3} />

        <Suspense fallback={null}>
          <Frame />
          {/* Front */}
          <PlaneMask stencilRef={1} position={[0, 0, 1]}>
            <Ladies
              stencilRef={1}
              color={FrontColor}
              floor={Show}
              model={FrontModel}
            />
          </PlaneMask>
          {/* Back */}
          <PlaneMask
            stencilRef={2}
            position={[0, 0, -1]}
            rotation={[0, Math.PI, 0]}
          >
            <Ladies
              stencilRef={2}
              color={BackColor}
              floor={Show}
              model={BackModel}
            />
          </PlaneMask>
          {/* Left */}
          <PlaneMask
            stencilRef={3}
            position={[-1, 0, 0]}
            rotation={[0, -Math.PI / 2, 0]}
          >
            <Ladies
              stencilRef={3}
              color={LeftColor}
              floor={Show}
              model={LeftModel}
            />
          </PlaneMask>
          <PlaneMask
            stencilRef={4}
            position={[1, 0, 0]}
            rotation={[0, Math.PI / 2, 0]}
          >
            <Ladies
              stencilRef={4}
              color={RightColor}
              floor={Show}
              model={RightModel}
            />
          </PlaneMask>
          <PlaneMask
            stencilRef={5}
            position={[0, 1, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <Ladies
              stencilRef={5}
              color={TopColor}
              floor={Show}
              model={TopModel}
            />
          </PlaneMask>
          <PlaneMask
            stencilRef={6}
            position={[0, -1, 0]}
            rotation={[Math.PI / 2, 0, 0]}
          >
            <Ladies
              stencilRef={6}
              color={BottomColor}
              floor={Show}
              model={BottomModel}
            />
          </PlaneMask>
        </Suspense>
      </Canvas>
    </>
  )
}
